spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=chaithh
spring.security.user.password=$2a$10$10XvfiN.uYP3W7h7.OUfSufSm995AbK6YCQSFyZg3MOU3VdzP6GpW